"""empty message

Revision ID: 4961d6a0cfd4
Revises: None
Create Date: 2014-10-12 04:03:46.090000

"""

# revision identifiers, used by Alembic.
revision = '4961d6a0cfd4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mafia_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roomNum', sa.Integer(), nullable=True),
    sa.Column('manager', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mafia_room')
    ### end Alembic commands ###
